capabilities:
  - provider: tuya
    type: climate-sensor
    id: 123 # bedroom
  - provider: tuya
    type: blinds-control
    id: 1234 # bedroom
  - provider: tuya
    type: climate-sensor
    id: 5678 # living
  - provider: fastmile
    type: router
    id: router
  - provider: utorrent
    type: torrent
    id: utorrent


status:
  - group: router
    items:
      - text: "ğŸ“¶"
        capabilities:
          - router
  - group: rooms
    items:
      - text: "ğŸ›"
        capabilities:
          - 123 # climate
          - 1234 # blinds
      - text: "ğŸ›‹"
        capabilities:
          - 5678 # climate
  - group: torrents
    items:
      - capabilities:
          - utorrent






